name: Run BigQuery Function

on: [push]

jobs:
  run-query:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the Node.js version your project requires

      - name: Install dependencies
        run: npm install


      - name: Set Google Application Credentials
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" | base64 -d > google-credentials.json || echo "$GOOGLE_CREDENTIALS" | base64 --decode > google-credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS=$PWD/google-credentials.json

      - name: Run BigQuery function
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
        run: node netlify/functions/get2.js  # Ensure this path is correct
